Tweaked network checking to look for device IP before restarting network stack

diff --git a/board/shredos/fsoverlay/usr/bin/nwipe_launcher b/board/shredos/fsoverlay/usr/bin/nwipe_launcher
--- a/board/shredos/fsoverlay/usr/bin/nwipe_launcher
+++ b/board/shredos/fsoverlay/usr/bin/nwipe_launcher
@@ -60,7 +60,7 @@ serial_number="$(lshw -class system -json | jq -r '.[0].serial')"
 # log "test log message"
 
 break_error () {
-    read -n 1 -p "Something has gone wrong. Show the above to TomC"
+    read -n 1 -p "Something has gone wrong. Show the above to TomC. Press any key to continue."
 }
 
 echo "[$(date)] lftp log" > lftp.log
@@ -92,8 +92,27 @@ fi
 mkdir /usr/output
 echo "[$(date)] Created /usr/output directory"
 
-## wait for network
-echo "[$(date)] Waiting for network"
+## check if device has ip on eth0,
+echo "[$(date)] Waiting for the network"
+has_ip=1
+while [ $has_ip -eq 1 ]; do
+    # pause to give services a chance to catch up
+    sleep 15
+    # ask ip for all IPv4 address and see if eth0 is present
+    ip -4 addr | grep eth0 > /dev/null
+    # grep exit status is 1 when string isn't found
+    has_ip=$?
+    if [ $has_ip -eq 1 ]; then
+        echo "[$(date)] Failed to get an IP address. Restarting network."
+        /etc/init.d/S40network restart > /dev/null
+        # pause to give the network scripts a chance to finish
+        sleep 15
+    fi
+done
+echo "[$(date)] Now have an IP address."
+
+## wait for network ()
+echo "[$(date)] Waiting for server"
 while [ $pinged -eq 0 ]; do
     ping -c 1 "$server_ip" > /dev/null 2>&1
     ping_exit_status=$?
